# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hassell/rpmbuild/lsrc/lug

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hassell/rpmbuild/lsrc/lug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hassell/rpmbuild/lsrc/lug/CMakeFiles /home/hassell/rpmbuild/lsrc/lug/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hassell/rpmbuild/lsrc/lug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lug-shared

# Build rule for target.
lug-shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lug-shared
.PHONY : lug-shared

# fast build rule for target.
lug-shared/fast:
	$(MAKE) -f lug/CMakeFiles/lug-shared.dir/build.make lug/CMakeFiles/lug-shared.dir/build
.PHONY : lug-shared/fast

#=============================================================================
# Target rules for targets named lug-static

# Build rule for target.
lug-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lug-static
.PHONY : lug-static

# fast build rule for target.
lug-static/fast:
	$(MAKE) -f lug/CMakeFiles/lug-static.dir/build.make lug/CMakeFiles/lug-static.dir/build
.PHONY : lug-static/fast

#=============================================================================
# Target rules for targets named basic

# Build rule for target.
basic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 basic
.PHONY : basic

# fast build rule for target.
basic/fast:
	$(MAKE) -f samples/CMakeFiles/basic.dir/build.make samples/CMakeFiles/basic.dir/build
.PHONY : basic/fast

#=============================================================================
# Target rules for targets named calc

# Build rule for target.
calc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calc
.PHONY : calc

# fast build rule for target.
calc/fast:
	$(MAKE) -f samples/CMakeFiles/calc.dir/build.make samples/CMakeFiles/calc.dir/build
.PHONY : calc/fast

#=============================================================================
# Target rules for targets named json

# Build rule for target.
json: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 json
.PHONY : json

# fast build rule for target.
json/fast:
	$(MAKE) -f samples/CMakeFiles/json.dir/build.make samples/CMakeFiles/json.dir/build
.PHONY : json/fast

#=============================================================================
# Target rules for targets named nonterminals

# Build rule for target.
nonterminals: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nonterminals
.PHONY : nonterminals

# fast build rule for target.
nonterminals/fast:
	$(MAKE) -f tests/CMakeFiles/nonterminals.dir/build.make tests/CMakeFiles/nonterminals.dir/build
.PHONY : nonterminals/fast

#=============================================================================
# Target rules for targets named leftrecursion

# Build rule for target.
leftrecursion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 leftrecursion
.PHONY : leftrecursion

# fast build rule for target.
leftrecursion/fast:
	$(MAKE) -f tests/CMakeFiles/leftrecursion.dir/build.make tests/CMakeFiles/leftrecursion.dir/build
.PHONY : leftrecursion/fast

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) -f tests/CMakeFiles/parser.dir/build.make tests/CMakeFiles/parser.dir/build
.PHONY : parser/fast

#=============================================================================
# Target rules for targets named predicates

# Build rule for target.
predicates: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 predicates
.PHONY : predicates

# fast build rule for target.
predicates/fast:
	$(MAKE) -f tests/CMakeFiles/predicates.dir/build.make tests/CMakeFiles/predicates.dir/build
.PHONY : predicates/fast

#=============================================================================
# Target rules for targets named terminals

# Build rule for target.
terminals: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 terminals
.PHONY : terminals

# fast build rule for target.
terminals/fast:
	$(MAKE) -f tests/CMakeFiles/terminals.dir/build.make tests/CMakeFiles/terminals.dir/build
.PHONY : terminals/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lug-shared"
	@echo "... lug-static"
	@echo "... basic"
	@echo "... calc"
	@echo "... json"
	@echo "... nonterminals"
	@echo "... leftrecursion"
	@echo "... parser"
	@echo "... predicates"
	@echo "... terminals"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

